interface Answers {
  [key: string]: string;
}

export const answers: Answers = {
  "pytanie": "Oczywiście, zapytaj śmiało!",
  "pogoda": "Aktualnie niestety nie potrafię dostarczać informacji o pogodzie",
  "dziękuję": "Nie ma sprawy! Jestem tu, aby pomóc",
  "jak się masz": "Miło, że pytasz. Wirtualnie, zawsze gotów do działania.",
  "żart": "Dlaczego komputerowi nigdy nie jest za zimno? Bo zawsze ma Windows!",
  "pomoc": "Jak mogę ci dzisiaj pomóc?",
  "pożegnanie": "Do zobaczenia! Życzę miłego dnia",
  "imie": "Jestem botem, niestety nie mam imienia. Jak mogę ci pomóc?",
  "ulubione jedzenie": "Nie jem, ale słyszałem, że pizza jest popularna. A ty?",
  "muzyka": "Muzyka to świetna sprawa! Jakie gatunki lubisz najbardziej?",
  "co u ciebie": "Tutaj wszystko w porządku, gotów na rozmowę!",
  "programowanie": "Programowanie to fascynujące! Jakie języki programowania znasz?",
  "co nowego": "Nie mam najnowszych wiadomości, ale jestem gotów na rozmowę",
  "Classic Rock": "Fajnie też lubię",
  "Hard Rock": "Fajnie też lubię",
  "Punk Rock": "Fajnie też lubię",
  "Alternative Rock": "Fajnie też lubię",
  "Indie Rock": "Fajnie też lubię",
  "Pop Rock": "Fajnie też lubię",
  "Synth-pop": "Fajnie też lubię",
  "Electropop": "Fajnie też lubię",
  "Indie Pop": "Fajnie też lubię",
  "K-pop (Korean Pop)": "Fajnie też lubię",
  "East Coast Hip-hop": "Fajnie też lubię",
  "West Coast Hip-hop": "Fajnie też lubię",
  "Trap": "Fajnie też lubię",
  "R&B": "Fajnie też lubię",
  "Grime": "Fajnie też lubię",
  "House": "Fajnie też lubię",
  "Techno": "Fajnie też lubię",
  "Trance": "Fajnie też lubię",
  "Dubstep": "Fajnie też lubię",
  "Drum and Bass": "Fajnie też lubię",
  "Traditional Country": "Fajnie też lubię",
  "Country Pop": "Fajnie też lubię",
  "Bluegrass": "Fajnie też lubię",
  "Americana": "Fajnie też lubię",
  "Outlaw Country": "Fajnie też lubię",
  "Swing": "Fajnie też lubię",
  "Bebop": "Fajnie też lubię",
  "Fusion": "Fajnie też lubię",
  "Smooth Jazz": "Fajnie też lubię",
  "Latin Jazz": "Fajnie też lubię",
  "Delta Blues": "Fajnie też lubię",
  "Chicago Blues": "Fajnie też lubię",
  "Electric Blues": "Fajnie też lubię",
  "Contemporary Blues": "Fajnie też lubię",
  "Blues Rock": "Fajnie też lubię",
  "Motown": "Fajnie też lubię",
  "Funk": "Fajnie też lubię",
  "Neo-Soul": "Fajnie też lubię",
  "Cześć": "Cześć, Jak ci mogę dzisiaj pomóc?",
  "Witaj": "Witaj, Jak ci mogę dzisiaj pomóc?",
  "Dzień dobry": "Dzień dobry, jak ci mogę dzisiaj pomóc?",
  "Dobry wieczór": "Dobry wieczór",
  "Witajcie": "Witaj, jak ci pomóc?",
  "Siema": "Siema, jak ci pomóc?",
  "Halo": "Halo, jak ci mogę pomóc?",
  "Hej": "Hej, jak ci mogę dzisiaj pomóc?",
  "Czołem": "Czołem, jak ci dzisiaj mogę pomóc?",
  "Cześć wszystkim": "Cześć, ale niestety jestem sam :{",
  "Hi there": "Hi, How can I help you?",
  "Hello": "Hello, how can I help you?",
  "Hey": "Hey, how can I help you?",
}
