interface Answers {
    [key: string]: string;
}

export const answers: Answers = {
    "pytanie": "Oczywiście, zapytaj śmiało!",
    "pogoda": "Aktualnie niestety nie potrafię dostarczać informacji o pogodzie",
    "dziękuję": "Nie ma sprawy! Jestem tu, aby pomóc",
    "jak się masz": "Miło, że pytasz. Wirtualnie, zawsze gotów do działania.",
    "żart": "Dlaczego komputerowi nigdy nie jest za zimno? Bo zawsze ma Windows!",
    "pomoc": "Jak mogę ci dzisiaj pomóc?",
    "pożegnanie": "Do zobaczenia! Życzę miłego dnia",
    "imie": "Jestem botem, niestety nie mam imienia. Jak mogę ci pomóc?",
    "ulubione jedzenie": "Nie jem, ale słyszałem, że pizza jest popularna. A ty?",
    "muzyka": "Muzyka to świetna sprawa! Jakie gatunki lubisz najbardziej?",
    "co u ciebie": "Tutaj wszystko w porządku, gotów na rozmowę!",
    "programowanie": "Programowanie to fascynujące! Jakie języki programowania znasz?",
    "co nowego": "Nie mam najnowszych wiadomości, ale jestem gotów na rozmowę",
    "Classic Rock": "Fajnie też lubię",
    "Hard Rock": "Fajnie też lubię",
    "Punk Rock": "Fajnie też lubię",
    "Alternative Rock": "Fajnie też lubię",
    "Indie Rock": "Fajnie też lubię",
    "Pop Rock": "Fajnie też lubię",
    "Synth-pop": "Fajnie też lubię",
    "Electropop": "Fajnie też lubię",
    "Indie Pop": "Fajnie też lubię",
    "K-pop (Korean Pop)": "Fajnie też lubię",
    "East Coast Hip-hop": "Fajnie też lubię",
    "West Coast Hip-hop": "Fajnie też lubię",
    "Trap": "Fajnie też lubię",
    "R&B": "Fajnie też lubię",
    "Grime": "Fajnie też lubię",
    "House": "Fajnie też lubię",
    "Techno": "Fajnie też lubię",
    "Trance": "Fajnie też lubię",
    "Dubstep": "Fajnie też lubię",
    "Drum and Bass": "Fajnie też lubię",
    "Traditional Country": "Fajnie też lubię",
    "Country Pop": "Fajnie też lubię",
    "Bluegrass": "Fajnie też lubię",
    "Americana": "Fajnie też lubię",
    "Outlaw Country": "Fajnie też lubię",
    "Swing": "Fajnie też lubię",
    "Bebop": "Fajnie też lubię",
    "Fusion": "Fajnie też lubię",
    "Smooth Jazz": "Fajnie też lubię",
    "Latin Jazz": "Fajnie też lubię",
    "Delta Blues": "Fajnie też lubię",
    "Chicago Blues": "Fajnie też lubię",
    "Electric Blues": "Fajnie też lubię",
    "Contemporary Blues": "Fajnie też lubię",
    "Blues Rock": "Fajnie też lubię",
    "Motown": "Fajnie też lubię",
    "Funk": "Fajnie też lubię",
    "Neo-Soul": "Fajnie też lubię",
    "Cześć": "Cześć, Jak ci mogę dzisiaj pomóc?",
    "Witaj": "Witaj, Jak ci mogę dzisiaj pomóc?",
    "Dzień dobry": "Dzień dobry, jak ci mogę dzisiaj pomóc?",
    "Dobry wieczór": "Dobry wieczór",
    "Dart": "Język programowania rozwijany przez Google, często stosowany w tworzeniu aplikacji Flutter.",
    "Shell scripting languages (np. Bash)": "Języki skryptowe używane do automatyzacji zadań systemowych w systemach operacyjnych.",
    "Scala": "Język programowania, który łączy funkcje obiektowe i funkcyjne, działający na platformie JVM.",
    "Groovy": "Język dynamiczny, często używany w środowisku Java, wspierający programowanie funkcyjne.",
    "HTML/CSS": "Języki używane do tworzenia struktur i stylizacji stron internetowych.",
    "SQL": "Język zapytań używany do zarządzania danymi w relacyjnych bazach danych.",
    "Assembly language": "Języki niskiego poziomu, używane do programowania komputerów bezpośrednio w języku maszynowym.",
    "Perl": "Język skryptowy, używany do przetwarzania tekstu, generowania raportów i automatyzacji zadań systemowych.",
    "Lua": "Lekki język skryptowy, często używany w grach wideo i systemach wbudowanych.",
    "Julia": "Język programowania stworzony do efektywnej analizy danych i obliczeń naukowych.",
    "Haskell": "Język funkcyjny, znany z zaawansowanych koncepcji takich jak monady, stosowany w programowaniu funkcyjnym.",
    "Cobol": "Język programowania używany głównie w biznesie i systemach korporacyjnych.",
    "Fortran": "Język programowania stosowany w naukach ścisłych, inżynierii i obliczeniach naukowych.",
    "Lisp": "Język programowania znany z manipulacji list i wsparcia dla programowania.",
    "Ada": "Język programowania stworzony dla zastosowań wysokoniebezpiecznych, szczególnie w obszarze systemów wbudowanych, lotniczych i obronnych.",
    "Witajcie": "Witaj, jak ci pomóc?",
    "Siema": "Siema, jak ci pomóc?",
    "Halo": "Halo, jak ci mogę pomóc?",
    "Hej": "Hej, jak ci mogę dzisiaj pomóc?",
    "Czołem": "Czołem, jak ci dzisiaj mogę pomóc?",
    "Cześć wszystkim": "Cześć, ale niestety jestem sam :{",
    "Hi there": "Hi, How can I help you?",
    "Hello": "Hello, how can I help you?",
    "Hey": "Hey, how can I help you?",
    "Paella": "Klasyczne danie hiszpańskie z ryżem, warzywami i często z owocami morza lub mięsem.",
    "Hamburger": "Placki mięsne, najczęściej z wołowiny, w bułce z różnymi dodatkami, takimi jak sałata, pomidor, ser, ketchup i majonez.",
    "Croissant": "Francuskie ciasto drożdżowe w kształcie półksiężyca, kruche i miękkie w środku.",
    "Curry": "Potrawa przygotowana z mięsa, warzyw lub ryb, gotowana z intensywnym sosem curry, popularna w kuchni indyjskiej i innych azjatyckich.",
    "Tacos": "Meksykańska przekąska składająca się z małych placków (tortilli), nadziewanych mięsem, warzywami i sosami.",
    "Dim Sum": "Chińskie przekąski, często podawane w małych porcjach, takie jak pierożki, bułeczki i inne dania gotowane na parze lub smażone.",
    "Gyros": "Greckie danie z mięsa, najczęściej wieprzowego, podawanego w cienkich plasterkach wraz z warzywami i sosem tzatziki w cieście pita.",
    "Kimchi": "Koreańska potrawa kiszona, zazwyczaj z kapusty pekińskiej i rzodkiewki, przyprawiona ostro-pikantnym sosem.",
    "Poutine": "Kanadyjska przekąska składająca się z frytek polanych sosem gravy i posypanych serem.",
    "Tom Yum": "Tajlandzka zupa ostryżowana, zazwyczaj z krewetkami, grzybami, trawą cytrynową i chilli.",
    "Feijoada": "Brazylijskie danie z czarnych fasoli i mięsa wieprzowego, kiełbasy i kiełbasy chorizo.",
    "Shakshuka": "Bliskowschodnie danie jajeczne w sosie pomidorowym z przyprawami.",
    "Borscht": "Rosyjska zupa buraczkowa, często podawana z kwaśną śmietaną.",
    "Fish and Chips": "Brytyjskie danie fast food składające się z filetów ryb panierowanych i frytek.",
    "Peking Duck": "Chińska potrawa, w której kaczka jest marynowana, gotowana, a następnie pieczona do uzyskania chrupiącej skórki.",
    "Goulash": "Węgierska potrawa mięsna, zazwyczaj z wołowiny, duszona z warzywami i przyprawami.",
    "Tiramisu": "Włoski deser warstwowy z kawą, serem mascarpone i biszkoptami.",
    "Rendang": "Indonezyjskie danie mięsne, duszone w intensywnych przyprawach i mleku kokosowym.",
    "Caesar Salad": "Zimna sałatka z sałaty rzymskiej, krakersów, sera parmezan, sosu Caesar i kawałków kurczaka.",
    "Nasi Goreng": "Indonezyjskie danie z duszonym ryżem, warzywami, jajkiem i często mięsem.",
    "Kebab": "Potrawa z Bliskiego Wschodu, składająca się z mięsa, warzyw i sosu, najczęściej podawana w cieście pita.",
    "Pho": "Wietnamska zupa rybna z makaronem ryżowym, mięsem, warzywami i ziołami.",
    "Pirogi": "Tradycyjne danie wschodnioeuropejskie, placki nadziewane różnymi farszami.",
    "Couscous": "Potrawa z kuskusu, charakterystyczna dla kuchni północnoafrykańskiej.",
    "Sauerbraten": "Niemieckie danie mięsne, marynowane i duszone, zazwyczaj podawane z sosem i kluskami ziemniaczanymi.",
    "Tandoori Chicken": "Indyjskie danie z kurczaka marynowanego w przyprawach i pieczonego w piecu tandoor.",
    "Mole Poblano": "Meksykański sos czekoladowo-pomidorowy, często podawany z kurczakiem.",
    "Moussaka": "Potrawa grecka, warstwowa zapiekanka z bakłażanów, mięsa",
    "Pierogi": "Małe kluski z nadzieniem, mogą być słodkie (np. z serem i ziemniakami, truskawkami) lub słone (np. z mięsem, kapustą i grzybami).",
    "Bigos": "Tradycyjne danie mięsne, znane również jako \"kapuśniak\", składające się z kiszonej kapusty, różnych mięs (często kiełbasy, wieprzowiny i wołowiny), grzybów i przypraw.",
    "Żurek": "Zupa kwasowa przygotowywana na bazie zakwasu żytniego, podawana z jajkiem, kiełbasą, ziemniakami i białą kiełbasą.",
    "Kotlet schabowy": "Schabowy panierowany i smażony, podawany z ziemniakami i surówką. Jedno z najbardziej popularnych dań mięsnych w Polsce.",
    "Barszcz czerwony": "Tradycyjna zupa czerwona przygotowywana z buraków, podawana z jajkiem i pasztecikiem.",
    "Kapuśniak": "Zupa kapuśniakowa przygotowywana z kiszonej kapusty, mięsa, ziemniaków i marchewki.",
    "Gołąbki": "Rulony z kapusty nadziewane mięsem i ryżem, gotowane w sosie pomidorowym.",
    "Kiełbasa": "Popularne polskie kiełbasy, takie jak kiełbasa kabanos czy kiełbasa krakowska.",
    "Placki ziemniaczane": "Placki przygotowywane z tartych ziemniaków, często podawane z kwaśną śmietaną.",
    "Zupa pomidorowa": "Klasyczna zupa pomidorowa z dodatkiem ryżu lub makaronu.",
    "Zrazy": "Smażone plastry mięsa nadziewane pieczarkami, ogórkami kiszonymi i boczkiem.",
    "Kaszanka": "Kiełbasa kaszanka przygotowywana z krwi wieprzowej, kaszy gryczanej i przypraw.",
    "Krokiety": "Roladki z farszem mięsnym lub warzywnym, panierowane i smażone.",
    "Makowiec": "Strucla nadziewana makiem i cukrem, często podawana na Święta.",
    "Naleśniki": "Cienkie placki podawane z różnymi nadzieniami, takimi jak twarożek, dżem czy śmietana.",
    "Oscypek": "Tradycyjny owczy ser produkowany w górach, często grillowany.",
    "Zupa ogórkowa": "Zupa przygotowywana z kiszonych ogórków, często z dodatkiem ziemniaków i kiełbasy.",
    "Kopytka": "Kluski ziemniaczane podawane z różnymi sosami, mięsem lub warzywami.",
    "Flaki": "Zupa z kawałkami podrobów, najczęściej podawana z bułką lub ziemniakami.",
    "Chłodnik": "Zimna zupa kwasowa z dodatkiem śmietany, ogórków, rzodkiewki i kopru.",
    "Pizza": "Placki cienko ciasta z różnymi nadzieniami, często pieczone w piecu opalanym drewnem.",
    "Pasta Carbonara": "Makaron z sosem carbonara, przygotowany z boczkiem, jajkami, parmezanem i pieprzem.",
    "Risotto": "Danie z ryżu gotowanego na bulionie, często z dodatkiem warzyw, sera lub owoców morza.",
    "Lasagne": "Warstwowa potrawa z makaronu lasagne, sosu mięsnego, beszamelu i sera.",

    "Bruschetta": "Plasterki grzanego chleba posmarowane czosnkiem, pomidorami i bazylią.",
    "Minestrone": "Warzywna zupa z dodatkiem makaronu lub ryżu.",
    "Spaghetti Bolognese": "Makaron spaghetti podawany z sosem mięsno-pomidorowym z dodatkiem warzyw.",
    "Caprese": "Sałatka z pomidorów, mozzarelli i świeżej bazylii, skropiona oliwą z oliwek.",
    "Osso Buco": "Duszone karkówki cielęcej z warzywami, serwowane z kością i szpikiem.",
    "Gnocchi": "Kluski ziemniaczane podawane z różnymi sosami.",
    "Cannelloni": "Rurki makaronowe nadziewane mięsem, warzywami lub serem, podawane z sosem pomidorowym.",
    "Panna Cotta": "Deser na bazie śmietany, cukru i żelatyny, często podawany z owocami lub sosem karmelowym.",
    "Frittata": "Omlet włoski z jajek, ziemniaków i innych składników, smażony na patelni.",
    "Arancini": "Kuleczki ryżowe nadziewane mięsem, sosem pomidorowym i serem, obtoczone w panierce i smażone.",
    "Panzanella": "Sałatka chlebowa z pomidorami, ogórkiem, cebulą i bazylią.",
    "Prosciutto e Melone": "Plastry szynki parmeńskiej podawane z kawałkami melona.",
    "Amatriciana": "Sos pomidorowy z boczkiem i cebulą, podawany z makaronem.",
    "Saltimbocca": "Cienkie plastry cielęcego mięsa obsmażane z szynką parmeńską i szałwią.",
    "Cicchetti": "Małe przekąski weneckie, podobne do hiszpańskich tapas.",
    "Cześć!": "Cześć, Jak ci mogę dzisiaj pomóc?",
    "Witaj!": "Witaj, Jak ci mogę dzisiaj pomóc?",
    "Dzień dobry!": "Dzień dobry, jak ci mogę dzisiaj pomóc?",
    "Dobry wieczór!": "Dobry wieczór",
    "Witajcie!": "Witaj, jak ci pomóc?",
    "Siema!": "Siema, jak ci pomóc?",
    "Halo!": "Halo, jak ci mogę pomóc?",
    "Hej!": "Hej, jak ci mogę dzisiaj pomóc?",
    "Czołem!": "Czołem, jak ci dzisiaj mogę pomóc?",
    "Cześć wszystkim!": "Cześć, ale niestety jestem sam :{",
    "Hi there!": "Hi, How can I help you?",
    "Hello!": "Hello, how can I help you?",
    "Hey!": "Hey, how can I help you?",

    "Contemporary R&B": "Fajnie też lubię",
    "Gospel": "Fajnie też lubię",
    "Roots Reggae": "Fajnie też lubię",
    "Dancehall": "Fajnie też lubię",
    "Dub": "Fajnie też lubię",
    "Ska": "Fajnie też lubię",
    "Reggaeton": "Fajnie też lubię",
    "Heavy Metal": "Fajnie też lubię",
    "Thrash Metal": "Fajnie też lubię",
    "Death Metal": "Fajnie też lubię",
    "Black Metal": "Fajnie też lubię",
    "Power Metal": "Fajnie też lubię",
    "Baroque": "Fajnie też lubię",
    "Classical Period": "Fajnie też lubię",
    "Romantic": "Fajnie też lubię",
    "Contemporary Classical": "Fajnie też lubię",
    "Opera": "Fajnie też lubię",
    "Traditional Folk": "Fajnie też lubię",
    "Folk Rock": "Fajnie też lubię",
    "Celtic Folk": "Fajnie też lubię",
    "World Folk": "Fajnie też lubię",
    "Afrobeat": "Fajnie też lubię",
    "Salsa": "Fajnie też lubię",
    "Bollywood": "Fajnie też lubię",
    "Flamenco": "Fajnie też lubię",
    "Kizomba": "Fajnie też lubię",
    "Hardcore Punk": "Fajnie też lubię",
    "Pop Punk": "Fajnie też lubię",
    "Post-punk": "Fajnie też lubię",
    "Punk Blues": "Fajnie też lubię",
    "Indie Folk": "Fajnie też lubię",
    "Dream Pop": "Fajnie też lubię",
    "Shoegaze": "Fajnie też lubię",
    "cześć": "Cześć jak ci mogę dzisiaj pomóc?"
}
